name: Test code check

on:
    pull_request:
        branches:
            - 'release/npi-base-latest'
            - 'release/npi-base-previous'
    workflow_call:

jobs:
    test_check:
        name: 🔎
        runs-on: ubuntu-latest
        steps:
            - run: echo "All checks passed successfully!"