name: PR checks before merging

on:
  # pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CircleCI Workflow
        id: test-analysis
        run: |
          CIRCLECI_TOKEN=${{ secrets.PS_CIRCLECI_TOKEN }}
          CIRCLECI_PROJECT_SLUG=${{ vars.CIRCLECI_PROJECT_SLUG }}
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')

          echo "Branch name: $BRANCH_NAME"
  
          # Trigger CircleCI workflow
          response=$(curl -sSL -X POST -H "Content-Type: application/json" -H "Circle-Token: $CIRCLECI_TOKEN" \
            -d "{\"branch\":\"$BRANCH_NAME\", \"parameters\":{\"trigger_branch\":\"$BRANCH_NAME\"}}" \
            "https://circleci.com/api/v2/project/$CIRCLECI_PROJECT_SLUG/pipeline")

          echo "CircleCI workflow result: $response"
  
          # Extract the CircleCI workflow ID from the response
          workflow_id=$(echo "$response" | jq -r '.id')
  
          echo "CircleCI workflow triggered. Workflow ID: $workflow_id"
  
          # Set a timeout (e.g., 30 minutes)
          timeout=30  # 30 seconds
          start_time=$(date +%s)
  
          # Wait for the completion of the CircleCI workflow
          while true; do
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))
  
            if [ $elapsed_time -ge $timeout ]; then
              echo "Timeout reached. CircleCI workflow did not complete within the specified time."
              exit 1  # Exit the workflow with an error status
            fi
  
            status=$(curl -sSL -H "Circle-Token: $CIRCLECI_TOKEN" "https://circleci.com/api/v2/pipeline/$workflow_id" | jq -r '.state')
  
            case $status in
              "success" | "failed" | "canceled")
                echo "CircleCI workflow completed with status: $status"
                break
                ;;
              *)
                echo "Waiting for CircleCI workflow to complete..."
                sleep 15  # Adjust the sleep interval as needed (15 seconds)
                ;;
            esac
          done
    
